trigger:
  branches:
    include:
      - main

pool:
  name: pr

stages:
- stage: Terraform
  displayName: "Terraform Stage"

  jobs:
  - job: TerraformJob
    displayName: "Terraform Init"

    steps:

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: "latest"

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: "azurerm"
        command: "init"
        backendServiceArm: "infra1"
        backendAzureRmResourceGroupName: "infra1"
        backendAzureRmStorageAccountName: "infra12"
        backendAzureRmContainerName: "infracon"
        backendAzureRmKey: "terraform.tfstate"